apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
    environment: staging
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: myapp 