name: Python build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m venev venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
